db.server=localhost:3306
db.name=expense_tracker
db.username=root
db.password=Akash@12345
db.driver=com.mysql.cj.jdbc.Driver


# for SSO

#spring.security.oauth2.client.registration.google.client-id=78576408822-tohbbanan47brqsnrocl2n8gvcsac73e.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.scope=email,profile