db.server=localhost:3306
db.name=expense_tracker
db.username=root
db.password=Akash@12345
db.driver=com.mysql.cj.jdbc.Driver


# for SSO

#spring.security.oauth2.client.registration.google.client-id=
#spring.security.oauth2.client.registration.google.client-secret=
#spring.security.oauth2.client.registration.google.scope=email,profile